# env initial values
ENV_NUMBER_OF_ROWS = 50
ENV_NUMBER_OF_COLS = 50
INITIAL_NUMBER_OF_SHEEP = 100
INITIAL_NUMBER_OF_WOLVES = 50
GREEN_GRASS_RATE = 0.5

# wolf initial values
WOLF_START_ENERGY = 20
WOLF_REPRODUCTION_RATE = 0.03
WOLF_GAIN_FROM_FOOD = 20
WOLF_LOSE_FROM_WALK = 1

# sheep initial values
SHEEP_START_ENERGY = 4
SHEEP_REPRODUCTION_RATE = 0.04
SHEEP_GAIN_FROM_FOOD = 4
SHEEP_LOSE_FROM_WALK = 1

# grass initial values
GRASS_REGROWTH_TIME = 30
